# ========================
# APPLICATION
# ========================
spring.application.name=OfflineApp

# ========================
# SERVER CONFIG
# ========================
server.port=8080
server.address=0.0.0.0

# ========================
# H2 DATABASE (FOR RENDER)
# ========================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT (to run data.sql)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# H2 Console (optional - for local testing)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================
# EMAIL CONFIG (GMAIL SMTP)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD   # ? paste your app password here

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# RAZORPAY CONFIG
# ========================
razorpay.key_id=rzp_test_SgRdbfoiG3LmdE
razorpay.key_secret=08oz9qlzx7CitXKSf2TyyABb


